// AUTO-GENERATED by scripts/optimize-images.mjs. Do not edit by hand.
// Run `npm run images:optimize` to regenerate.
export interface ResponsiveEntry {
  widths: number[];
  avif: string[];
  webp: string[];
  fallback: string[];
  originalWidth: number;
}

export const RESPONSIVE_IMAGES: Record<string, ResponsiveEntry> = {
  "/projects/ai-study-buddy/screenshot.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/ai-study-buddy/screenshot-640.avif",
      "/projects/ai-study-buddy/screenshot-1024.avif",
      "/projects/ai-study-buddy/screenshot-1600.avif"
    ],
    "webp": [
      "/projects/ai-study-buddy/screenshot-640.webp",
      "/projects/ai-study-buddy/screenshot-1024.webp",
      "/projects/ai-study-buddy/screenshot-1600.webp"
    ],
    "fallback": [
      "/projects/ai-study-buddy/screenshot-640.png",
      "/projects/ai-study-buddy/screenshot-1024.png",
      "/projects/ai-study-buddy/screenshot-1600.png"
    ],
    "originalWidth": 1915
  },
  "/projects/cartify/home.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/cartify/home-640.avif",
      "/projects/cartify/home-1024.avif",
      "/projects/cartify/home-1600.avif"
    ],
    "webp": [
      "/projects/cartify/home-640.webp",
      "/projects/cartify/home-1024.webp",
      "/projects/cartify/home-1600.webp"
    ],
    "fallback": [
      "/projects/cartify/home-640.png",
      "/projects/cartify/home-1024.png",
      "/projects/cartify/home-1600.png"
    ],
    "originalWidth": 1898
  },
  "/projects/cartify/mobile-view.png": {
    "widths": [
      387
    ],
    "avif": [
      "/projects/cartify/mobile-view-387.avif"
    ],
    "webp": [
      "/projects/cartify/mobile-view-387.webp"
    ],
    "fallback": [
      "/projects/cartify/mobile-view-387.png"
    ],
    "originalWidth": 387
  },
  "/projects/cartify/products.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/cartify/products-640.avif",
      "/projects/cartify/products-1024.avif",
      "/projects/cartify/products-1600.avif"
    ],
    "webp": [
      "/projects/cartify/products-640.webp",
      "/projects/cartify/products-1024.webp",
      "/projects/cartify/products-1600.webp"
    ],
    "fallback": [
      "/projects/cartify/products-640.png",
      "/projects/cartify/products-1024.png",
      "/projects/cartify/products-1600.png"
    ],
    "originalWidth": 1893
  },
  "/projects/researchgpt/architecture-blueprint.png": {
    "widths": [
      640,
      1024
    ],
    "avif": [
      "/projects/researchgpt/architecture-blueprint-640.avif",
      "/projects/researchgpt/architecture-blueprint-1024.avif"
    ],
    "webp": [
      "/projects/researchgpt/architecture-blueprint-640.webp",
      "/projects/researchgpt/architecture-blueprint-1024.webp"
    ],
    "fallback": [
      "/projects/researchgpt/architecture-blueprint-640.png",
      "/projects/researchgpt/architecture-blueprint-1024.png"
    ],
    "originalWidth": 1536
  },
  "/projects/sanjivani/app-preview.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/sanjivani/app-preview-640.avif",
      "/projects/sanjivani/app-preview-1024.avif",
      "/projects/sanjivani/app-preview-1600.avif"
    ],
    "webp": [
      "/projects/sanjivani/app-preview-640.webp",
      "/projects/sanjivani/app-preview-1024.webp",
      "/projects/sanjivani/app-preview-1600.webp"
    ],
    "fallback": [
      "/projects/sanjivani/app-preview-640.png",
      "/projects/sanjivani/app-preview-1024.png",
      "/projects/sanjivani/app-preview-1600.png"
    ],
    "originalWidth": 1920
  },
  "/projects/studysnap/ai-assistant.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/studysnap/ai-assistant-640.avif",
      "/projects/studysnap/ai-assistant-1024.avif",
      "/projects/studysnap/ai-assistant-1600.avif"
    ],
    "webp": [
      "/projects/studysnap/ai-assistant-640.webp",
      "/projects/studysnap/ai-assistant-1024.webp",
      "/projects/studysnap/ai-assistant-1600.webp"
    ],
    "fallback": [
      "/projects/studysnap/ai-assistant-640.png",
      "/projects/studysnap/ai-assistant-1024.png",
      "/projects/studysnap/ai-assistant-1600.png"
    ],
    "originalWidth": 2880
  },
  "/projects/studysnap/dark-dashboard.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/studysnap/dark-dashboard-640.avif",
      "/projects/studysnap/dark-dashboard-1024.avif",
      "/projects/studysnap/dark-dashboard-1600.avif"
    ],
    "webp": [
      "/projects/studysnap/dark-dashboard-640.webp",
      "/projects/studysnap/dark-dashboard-1024.webp",
      "/projects/studysnap/dark-dashboard-1600.webp"
    ],
    "fallback": [
      "/projects/studysnap/dark-dashboard-640.png",
      "/projects/studysnap/dark-dashboard-1024.png",
      "/projects/studysnap/dark-dashboard-1600.png"
    ],
    "originalWidth": 2880
  },
  "/projects/studysnap/mobile-dashboard.png": {
    "widths": [
      640
    ],
    "avif": [
      "/projects/studysnap/mobile-dashboard-640.avif"
    ],
    "webp": [
      "/projects/studysnap/mobile-dashboard-640.webp"
    ],
    "fallback": [
      "/projects/studysnap/mobile-dashboard-640.png"
    ],
    "originalWidth": 780
  },
  "/projects/studysnap/note-editor.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/studysnap/note-editor-640.avif",
      "/projects/studysnap/note-editor-1024.avif",
      "/projects/studysnap/note-editor-1600.avif"
    ],
    "webp": [
      "/projects/studysnap/note-editor-640.webp",
      "/projects/studysnap/note-editor-1024.webp",
      "/projects/studysnap/note-editor-1600.webp"
    ],
    "fallback": [
      "/projects/studysnap/note-editor-640.png",
      "/projects/studysnap/note-editor-1024.png",
      "/projects/studysnap/note-editor-1600.png"
    ],
    "originalWidth": 2880
  },
  "/projects/studysnap/revision-calendar.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/studysnap/revision-calendar-640.avif",
      "/projects/studysnap/revision-calendar-1024.avif",
      "/projects/studysnap/revision-calendar-1600.avif"
    ],
    "webp": [
      "/projects/studysnap/revision-calendar-640.webp",
      "/projects/studysnap/revision-calendar-1024.webp",
      "/projects/studysnap/revision-calendar-1600.webp"
    ],
    "fallback": [
      "/projects/studysnap/revision-calendar-640.png",
      "/projects/studysnap/revision-calendar-1024.png",
      "/projects/studysnap/revision-calendar-1600.png"
    ],
    "originalWidth": 2880
  },
  "/projects/studysnap/voice-notes.png": {
    "widths": [
      640,
      1024,
      1600
    ],
    "avif": [
      "/projects/studysnap/voice-notes-640.avif",
      "/projects/studysnap/voice-notes-1024.avif",
      "/projects/studysnap/voice-notes-1600.avif"
    ],
    "webp": [
      "/projects/studysnap/voice-notes-640.webp",
      "/projects/studysnap/voice-notes-1024.webp",
      "/projects/studysnap/voice-notes-1600.webp"
    ],
    "fallback": [
      "/projects/studysnap/voice-notes-640.png",
      "/projects/studysnap/voice-notes-1024.png",
      "/projects/studysnap/voice-notes-1600.png"
    ],
    "originalWidth": 2880
  }
};
